### PR TITLE
feat: provide overriding by :root in projects

### PR DESCRIPTION
**Pull request by pspaczek**
# Related issue

Closes #

# Scope of work

Change `:root` in global variables to `html` because `html` has the lowest specificity, and users in their project can use `:root {}`instead `#app` od `__nuxt` to override storefront-ui styles.
It should solve this issue [Customizing styles](https://docs.storefrontui.io/?path=/story/setup-css-customization--page#customizing-styles )
Please test this PR in SSR app, for static vue app it's work's fine :) 

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [x] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by Baroshem** [comment]
Hi @pspaczek 

Thanks for this PR. We will review it next week. 
PS I have read your post about :root and html and I wanted to implement that but here you are with a ready PR ;)

**Comment by pspaczek** [comment]
You're welcome. After watch your last video about customization in storefront-ui where I saw this `#app` 'hack' I thought I could fix it. And here we go! :)

**Comment by aniamusial** [comment]
praise: nice work @pspaczek :)

**Comment by aniamusial** [comment]
possible breaking change, so moving to 0.12.0 :)

**Review by justyna-13 — APPROVED** [review]
Before merge: changelog + migration guide

**Review by AdamPawlinski — APPROVED** [review]

**Review by justyna-13 — APPROVED** [review]

**Pull request closed without merging**
