### PR TITLE
[WIP] feat: progressive lazy loading using lozad

### LINKED ISSUE #1417: [FEATURE] progressive loading for images
**Describe how this feature will help us improve**
- Images should have placeholder visible before loading image.
- When the image is in loading progress should look like (ugly -> beauty / blurred -> sharp)
This feature will help load images faster and prettier eg. without empty places and jumping content.

**Is your proposal related to a problem?**
Describe the issue or type its number

**Describe the solution you'd considered**
Storefront UI library should have its own implementation of [progressive image loading](https://github.com/craigbuckler/progressive-image.js)
this solution is  [explained here](https://www.sitepoint.com/how-to-build-your-own-progressive-image-loader/)

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue
Closes #1417 

# Scope of work
Fix in SfImage code to make possible progressive loading. Added story to show how can it be used. 

# Screenshots of visual changes
image

image

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
Instead of applying new library as proposed, I would consider using lozad js to add placeholder for lazy loaded images. I added story in storybook to show how it works. Can you please take a look @mayashavin? @filrak also mention adding possibility to use native lazy loading as the option in SfImage wdyt @mayashavin?

**Comment by mayashavin** [comment]
@AdamPawlinski for lazy loading, we can use the native one with passing `loading="lazy` to the image component itself. There is no need for extra prop :). About adding lozadjs for the placeholder, tbh I'm not keen on using third party for such small feature. You can create another image as placeholder and hide/display it if the loading of the other image is not in progress/done but listening to the event 'load' of image component. LMK if you want me to elaborate further.

**Comment by AdamPawlinski** [comment]
@mayashavin lozadjs was added before to use lazy loading and I just used. Do I understand well and you suggest to get rid of this lib completely and use native loading?

**Comment by mayashavin** [comment]
@AdamPawlinski yes, I don't see a need for a third-party lib for something is native to browser :)

**Comment by AdamPawlinski** [comment]
It's no longer needed as there is already a new API for SfImage implemented.

**Pull request closed without merging**
