### PR TITLE
feat: changed the order of css custom properties addon

### LINKED ISSUE #2149: [FEATURE] Docs: Switch tabs order in docs
**Describe how this feature will help us improve**
Change tabs order to have docs first and move `Css Custom Properties` addon next to `Controls` to be more available for users.  
image

image

Issue connected with  #2040.

**Is your proposal related to a problem?**
No.

**Describe the solution you'd considered**

**Additional context**
Anything you would like to add but was not sure which section it fits.

### PR DESCRIPTION
**Pull request by ymaheshwari1**
# Related issue

Closes #2149 

# Scope of work

Changed the order of addons in storybook main.js

# Screenshots of visual changes

After:
image

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by justyna-13 — COMMENTED** [review]
Looks good 👍 could you add information about this change in our changelog for `0.12.1`?

**Comment by ymaheshwari1** [comment]
> Looks good 👍 could you add information about this change in our changelog for `0.12.1`?

Done @justyna-13

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 Great, would you like to switch the order of `canvas` and `docs` in other PR, as well?

**Review by AdamPawlinski — APPROVED** [review]

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 Great, would you like to switch the order of `canvas` and `docs` in other PR, as well?

Sure

**Review by aniamusial — APPROVED** [review]
Nice work!

**Pull request merged**
