### PR TITLE
fix: start correcting nuxt error css variable

### LINKED ISSUE #1390: [BUG] css-loader warning
**Describe the bug**
css-loader  warning

**How to reproduce**
1. install quasar cli (A Vue framework)
2. install storefront-ui
3. run

WARNING  Compiled with 1 warnings                                                                                                                                                                                            5:35:19 PM

 warning  in ./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue?vue&type=style&index=0&lang=scss&

Module Warning (from ./node_modules/css-loader/dist/cjs.js):
Warning

(47:5) Unable to find uri in 'background: var(--select-option-background, var(--select-option-background-image, url("")) var(--select-option-background-color, var(--c-white)) no-repeat var(--select-option-background-position, 0% 0%))'

 @ ./node_modules/vue-style-loader??ref--8-oneOf-2-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-2-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-2-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-2-3!./node_modules/@quasar/app/lib/webpack/loader.quasar-scss-variables.js!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue?vue&type=style&index=0&lang=scss& 4:14-531 14:3-18:5 15:22-539
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue?vue&type=style&index=0&lang=scss&
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfSelect/SfSelect.vue
 @ ./node_modules/@storefront-ui/vue/index.js
 @ ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/pages/Index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from 
 App · Opening default browser at http://localhost:8080

### PR DESCRIPTION
**Pull request by f3ltron**
# Related issue

Closes #1390 

# Scope of work

its just giving the opportunity to implement it into nuxt components. It works good but i can't use css.

I am new with vue storefront and didn't spend too much time on it

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [ ] Run tests and docs There are fails on test i have no ideas why ?
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
Can you please take a look on 0.9.0 version of SFUI? Is the problem you mentioned disappears or not?

**Comment by f3ltron** [comment]
Now by following the getting started i have focus directive is not defined that is called inside SFButton

**Comment by AdamPawlinski** [comment]
Unfortunately you are right, there is a bug, so we have to prepare patch for this.

**Comment by AdamPawlinski** [comment]
It should be solved by https://github.com/DivanteLtd/storefront-ui/pull/1459. But I'm not closing it till it's not tested after releasing.

**Comment by Baroshem** [comment]
The issue was closed. I also was not able to reproduce the issue with the current version.

**Pull request closed without merging**
