### PR TITLE
fix: bug SfTextArea in Form

### PR DESCRIPTION
**Pull request by ejgonzalez17**
# Related issue

#2175 
- SfTextarea in Form - too big on mobile view

# Scope of work
Solution of the Bug in Textarea in Form where its size was changed for its coupling in different screen sizes

# Screenshots of visual changes

- A video is attached where the dimension correction of the "Textarea in Form" is shown in different screen sizes

https://user-images.githubusercontent.com/70716664/147297528-f799ef73-7486-4bd1-8a77-cfa40242436d.mov

- Evidence in images
Screen Shot 2021-12-23 at 3 11 44 PM
Screen Shot 2021-12-23 at 3 10 57 PM

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [x]  I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by AdamPawlinski — CHANGES_REQUESTED** [review]
Hi @ejgonzalez17, thanks for your contribution, but it need some changes. Can you please apply your changes to the form template and not to the components itself because now this fixes cause such results in SfTextarea component: 
Screenshot from 2021-12-27 09-05-47


Screenshot from 2021-12-27 09-01-07

Thanks once again for your commitment :)

**Comment by ejgonzalez17** [comment]
Sure, I'll make the changes, thanks for the correction =)

**Comment by ejgonzalez17** [comment]
Hi I just moved the changes to the request place =) , I remain attentive to your comments.

**Review by justyna-13 — APPROVED** [review]
Looks great! :rocket:  Could you also add info about this change in our changelog? You can find it in `v0.12.0.stories.mdx` :slightly_smiling_face:

**Comment by ejgonzalez17** [comment]
Hi 🙂, I already added the changes to the document v0.12.0.stories.mdx.

**Review by AdamPawlinski — APPROVED** [review]

**Pull request merged**
