### PR TITLE
feat: provide an option to exclude closing button for SfNotification

### LINKED ISSUE #1765: [FEATURE] Provide an option to exclude closing button for SfNotification component
**Describe how this feature will help us improve**
I find it useful to have an option to exclude the closing button for SfNotification component, in case if it's a static notification, or it couldn't be dismissed. 

**Is your proposal related to a problem?**
In order to avoid showing the closing button with the current component, I had to pass an empty `div` to the `close` slot, which doesn't look nice. 

**Describe the solution you'd considered**
I think it would be nice to have a prop e.g. "Persistent", which would be a switcher for the closing button. An example code attached.

photo_2021-04-10_17-51-42

### PR DESCRIPTION
**Pull request by DavidGolodetsky**
# Related issue
Closes #1765

# Scope of work
Added persistent prop to render close slot conditionally.

# Checklist

- [x] No commented blocks of code left
- [ ] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented

### CODE REVIEW

**Comment by atlantis-vsf** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs  or, to disable this message, set --silence-fork-pr-errors

**Review by Baroshem — COMMENTED** [review]
@DavidGolodetsky 
PR looks good. Please just add the changelog so that we could merge this PR :)

**Comment by DavidGolodetsky** [comment]
Thank you! Fixed that

**Review by Baroshem — APPROVED** [review]

**Comment by Baroshem** [comment]
@DavidGolodetsky 
You merged develop to your branch and that should not be done. Our develop is out of the scope of our releases. We will probably change it in our next release to have more like branch -> develop -> master flow. For now, please revert your latest commit with merging develop to your branch.

**Comment by DavidGolodetsky** [comment]
oops, sorry missed that

**Comment by Baroshem** [comment]
There are still ~150 commits. They must be reduced to match the current 0.10.9. We cannot merge that.

**Comment by DavidGolodetsky** [comment]
I guess I'll just recreate a PR

**Pull request closed without merging**
