### PR TITLE
fix: link in the documentation(#1749)

### LINKED ISSUE #1749: [BUG] Some links in the docs are not working
**Describe the bug**
Link to some part of the docs are not working as expected.

**How to reproduce**
1. Go to https://docs.storefrontui.io/?path=/story/setup-installation--page#customization
2. Click on the link in the section (`here`)

**Expected behavior**
We should get redirected to the specific page in the doc

**Actual behavior**
Currently getting a blank page.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by ymaheshwari1**
# Related issue

Closes #1749 

# Scope of work
Updated link in documentation

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by Baroshem** [comment]
Hi @ymaheshwari1 
Is your PR ready for review? :)

**Comment by ymaheshwari1** [comment]
> Hi @ymaheshwari1
> Is your PR ready for review? :)

Hi @Baroshem, I am working on it and will try to update the PR as soon as possible.

**Review by Baroshem — APPROVED** [review]
Looks good to me! @justyna-13 could you please check it as well? :)

**Review by justyna-13 — APPROVED** [review]
Good job @ymaheshwari1 :slightly_smiling_face:

**Pull request merged**
