### PR TITLE
refactor: replace has-badge and badge-label props

### LINKED ISSUE #1473: Redundant props - hasBadge and badgeLabel
Saw we have `badgeLabel` and `hasBadge` in Icon. We don't need both, if there is a badge, a label must be presented, else, there is no label needed. We only need `badge` as a prop, and render only if it has value.

### PR DESCRIPTION
**Pull request by daksamit**
# Related issue

Closes #1473 

# Scope of work

I replaced both `has-badge` and `badge-label` props with single `badge` prop and check if length of string > 0.
Regarding [maya's](https://github.com/DivanteLtd/storefront-ui/issues/1473#issuecomment-718240236) comment SfBadge should be removed from SfIcon completely and implemented in different way.

I will remove badges, related scss and fix stories using SfIcon with badges examples. 

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [x] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component 
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by daksamit** [comment]
By the way, I fixed storybook SfIcon props (added icon size for knobs) and missing :disabled for variant with slot.
I'm not sure if :icon prop should be added if we use slot for SfCircleIcon ?

**Comment by daksamit** [comment]
Moreover [SfHeader](https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfHeader/SfHeader.vue)
contains SfIcon with `has-badge` and `badge-label` props with related computed values and props: `wishlistHasProducts`, `wishlistItemsQty`, `cartHasProducts` and `cartItemsQty`.
Should it refactored? I mean i.e:
```
                <SfIcon
                  class="sf-header__icon"
                  :icon="wishlistIcon"
                  :has-badge="wishlistHasProducts"
                  :badge-label="wishlistItemsQty"
                  size="1.25rem"
                  :class="{
                    'sf-header__icon is-active': activeIcon === 'wishlist',
                  }"
                />
```
without badge props? In different way with badges?

**Comment by mayashavin** [comment]
@daksamit Sorry for the late reply. Yes it should be refactored also, without the badge props. We can make a wrapper component where sfbadge will be displayed on top of sficon when needed

**Comment by mayashavin** [comment]
I closed this since we already remove sfBadge from sficon :)

**Pull request closed without merging**
