### PR TITLE
fix: #1782 - SfGallery - missing alt for an image

### PR DESCRIPTION
**Pull request by loongluangkhot**
# Related issue
https://github.com/vuestorefront/storefront-ui/issues/1782
Closes #

# Scope of work
Edited startZoom method in the component to store the entire `picture` object in `this.pictureSelected` instead of just the url, so that the `alt` property is accessible in the template. Also added computed property `pictureSelectedUrl` to get url using the old logic. Some changes on the template to add `alt` prop to the problematic SfImage.

# Screenshots of visual changes

Before fix: red dotted border around the zoomed image due to the missing alt
Screenshot 2021-05-05 at 10 57 08 PM

After fix: no red dotted border
Screenshot 2021-05-05 at 11 00 00 PM

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by loongluangkhot** [comment]
@justyna-13 sorry to tag you here. I read on the contributing guide that i should add a reviewer and/or add label `review required`, but I don't seem to be able to do any of those on my side. Am i missing something?

**Comment by justyna-13** [comment]
@loongluangkhot no worries :slightly_smiling_face: you've done everything great! Thanks for this PR - our team will check it tomorrow :) If you would like to take another task just let us know :) We really appreciate your help!

**Review by justyna-13 — APPROVED** [review]
:+1:

**Review by AdamPawlinski — APPROVED** [review]
Looks good :)

**Pull request merged**
