### PR TITLE
feat: change the docs tab to the first place in toolbar

### LINKED ISSUE #2149: [FEATURE] Docs: Switch tabs order in docs
**Describe how this feature will help us improve**
Change tabs order to have docs first and move `Css Custom Properties` addon next to `Controls` to be more available for users.  
image

image

Issue connected with  #2040.

**Is your proposal related to a problem?**
No.

**Describe the solution you'd considered**

**Additional context**
Anything you would like to add but was not sure which section it fits.

### PR DESCRIPTION
**Pull request by ymaheshwari1**
# Related issue
Closes #2149 

# Scope of work

- Defined index of docs tab (reference:l https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#reordering-docs-tab-first)
- Changed viewMode to docs to make docs to open on initial load (reference: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#controlling-a-storys-view-mode)

# Screenshots of visual changes

After:
image

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [x] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by ymaheshwari1** [comment]
Having an issue that on initial load getting an error in the console, but I don't think it's affecting anything on UI part
image

**Review by AdamPawlinski — APPROVED** [review]
@ymaheshwari1 Great! Could you please add the changelog note? Looks good, and I agree that, we can deal with this error in the future.

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 Great! Could you please add the changelog note? Looks good, and I agree that, we can deal with this error in the future.

Done @AdamPawlinski

**Review by justyna-13 — COMMENTED** [review]
Looks great @ymaheshwari1 :) could you move information about this change to our new changelog for 0.12.2 version? You can find it here https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx

**Comment by ymaheshwari1** [comment]
> Looks great @ymaheshwari1 :) could you move information about this change to our new changelog for 0.12.2 version? You can find it here https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx

Yes, sure

**Comment by ymaheshwari1** [comment]
@justyna-13 Changed changelog to 0.12.2
Also, have a doubt that the css custom properties work (#2241) got merged and released in 0.12.1 but the release notes are not present in 0.12.1.

**Comment by AdamPawlinski** [comment]
@ymaheshwari1 I think they are in the changelog, but we have released two release notes for 0.12.1 by mistake. 
Screenshot from 2022-02-09 08-44-03

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 I think they are in the changelog, but we have released two release notes for 0.12.1 by mistake. Screenshot from 2022-02-09 08-44-03

They are not in the changelog,
I am talking about this change
https://github.com/vuestorefront/storefront-ui/pull/2241/files#diff-01db2c6bd3e3546f6902e9a5f8a30b7f87937015e1b61c7ca4aa36d1dd3e7837

**Review by aniamusial — APPROVED** [review]

**Pull request merged**
