### PR TITLE
feat: add mixins to change breakpoint and generate classes

### LINKED ISSUE #1260: [BUG] Add possibility to change breakpoints
**Describe the bug**
There are to main breakpoints mixins used in SFUI for-mobile and for-desktop which have statically added value $desktop-min.  

**How to reproduce**
Run the project with SFUI and try to change breakpoint value. 

**Expected behavior**
There should be possibility for users to change these value in relation to current project needs globally. 

**Actual behavior**
Breakpoints are set once by adding scss variable in the helper.

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue

Closes #1260

# Scope of work
Added mixin to generate breakpoint classes with new resolution and added the possibility to pass a resolution to `for-mobile` and `for-desktop` mixin. 

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by justyna-13 — APPROVED** [review]

**Comment by AdamPawlinski** [comment]
I added the script to change the breakpoint on the third-party project. In order to test it you need to link the package and run the code: `yarn change-breakpoint` with the value of new breapoint in pixels without adding `px` like so: `yarn change-breakpoint 800` inside `node_modules` in `@strofront-ui/vue` folder. It should change this breakpoint in every `for-desktop` and `for-mobile` mixin used in SFUI. It doesn't change the value of `smartphone-only` and 'desktop-only` classes. Please try it on vue and nuxt project.

**Review by justyna-13 — COMMENTED** [review]
I wonder if there is any reason why we need changes in components styles - `@include for-desktop($breakpoint) `.  Can't we change just breakpoint? :)

**Comment by AdamPawlinski** [comment]
> I wonder if there is any reason why we need changes in components styles - `@include for-desktop($breakpoint) `. Can't we change just breakpoint? :)

Okay you are right, I added it in the first version of the script which used regex to find all mixins in components and in styles.

**Comment by AdamPawlinski** [comment]
> I wonder if there is any reason why we need changes in components styles - `@include for-desktop($breakpoint) `. Can't we change just breakpoint? :)

I removed the `$breakpoint` variable from style files. Yiu can check it.

**Review by justyna-13 — COMMENTED** [review]
@AdamPawlinski and what do you think about removing these changes from pages too?

**Review by justyna-13 — APPROVED** [review]

**Pull request merged**
