### PR TITLE
feat: SfSkeleton

### LINKED ISSUE #1607: [FEATURE] SfSkeleton
**Describe how this feature will help us improve**
Placeholder/Skeleton for other component like Image, details while the info is being loaded.

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue

Closes #1607 

# Scope of work

# Screenshots of visual changes

Screenshot from 2021-03-02 10-50-32
Screenshot from 2021-03-02 10-50-40

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by Baroshem** [comment]
I am not sure but there is a black vertical line in some cases of SfSkeleton
https://user-images.githubusercontent.com/37120330/109929742-1c4bd500-7cc7-11eb-8624-9104fc02d7ac.mov

**Review by Baroshem — DISMISSED** [review]
Well done!

**Review by Baroshem — APPROVED** [review]
I approve, @AdamPawlinski please take a look 😉

**Review by AdamPawlinski — APPROVED** [review]
Looks very relaxing when in pulsate mode :) 
Very well done.

**Pull request merged**
