### PR TITLE
fix: memory leak between navigation

### LINKED ISSUE #2400: [BUG] Memory leak with lazy loaded images
**Describe the bug**
JS heap size and _detached_ DOM nodes amount increase during navigation

**How to reproduce**

1. Open `memory` panel in chrome devtools, run the garbage collection, then take heap snapshot,
2. Navigate between multiple pages
3. Run the garbage collection and take a heap snapshot again, filter by "Detached"

**Expected behavior**
Detached nodes are removed from memory.

**Actual behavior**
JS heap size increase, garbage collection do not release unused nodes from memory

**Screenshots**
image

**Devices (please complete the following information):**
 - Browser: Chromium-based [Chrome, Edge]

**Additional context**
Related issues [link](https://github.com/vuejs/core/issues/5278)

### PR DESCRIPTION
**Pull request by marc-arnoult**
# Related issue
https://github.com/vuestorefront/storefront-ui/issues/2157
https://github.com/vuejs/vue/issues/10473

Closes #2400

# Scope of work
After seeing a consequent memory leak in our application, i found 2 issues : 

- It seem that component from the carousel is not destroyed because of the closure of glide event listener.
- The functional breadcrumbs component seems to retain in the memory the DOM of multiple pages.

For the functional component i'm not sure exactly why, it's very hard to debug with a huge Nuxt project.

# Screenshots of visual changes

Before: 
Capture d’écran 2022-05-08 à 14 48 56

After:

Capture d’écran 2022-05-08 à 14 48 59

:warning: The **Garbage collector** seems to be used a lot, there is maybe some work to do here.
:warning: There is maybe other functionals components to refactor.

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by Razz21** [comment]
Edge browser offers nice tool for debugging DOM leaks https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks

**Comment by marc-arnoult** [comment]
@Razz21 i didn't know this tool from Edge browser, thanks for the tips !

It seems to be well garbage collected from my POV. You will find more screenshots here : 

**Memory**
Before : 
Capture d’écran 2022-05-09 à 14 52 26
After : 
Capture d’écran 2022-05-09 à 14 52 18

**Elements**
Before: 
Capture d’écran 2022-05-09 à 14 49 44

After: 
Capture d’écran 2022-05-09 à 14 49 49

( Theses nodes seems to be specific to our project )

**Comment by aniamusial** [comment]
Hi @marc-arnoult thank you for contribution! Can you please resolve the conflicts? :)

**Review by aniamusial — APPROVED** [review]

**Comment by aniamusial** [comment]
Hey @marc-arnoult seems like some lint fix is required - can you have a look?

**Comment by marc-arnoult** [comment]
> Hey @marc-arnoult seems like some lint fix is required - can you have a look?

Hi @aniamusial, yes i will do it today !

**Comment by marc-arnoult** [comment]
@aniamusial it should be good now.

**Review by justyna-13 — APPROVED** [review]

**Comment by AdamPawlinski** [comment]
@marc-arnoult Hi, thanks for your cotribution. I know it was a long time ago, but can you resolve lint issues? I'd like to merge this PR finally :) Thanks in advance.

**Pull request closed without merging**
