### PR TITLE
feat: lazy load SfIcon component

### LINKED ISSUE #2295: [FEATURE] Change the way we import icons into projects
**Describe how this feature will help us improve**
Currently each time we import icons we import all of them, which is very bad for performance. We should find a solution to import only the svgs we need. 

**Is your proposal related to a problem?**
No

**Describe the solution you'd considered**
Exporting single svgs instead of the whole object?

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-83) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by RafalDobrowolski**
# Related issue

Closes #2295
# Scope of work

Add lazy loading for `SfIcon` component

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by AdamPawlinski — COMMENTED** [review]
@RafalDobrowolski Looks like it all works for me, really great work :+1: It would be nice to have tests adjusted to these changes.

**Review by AdamPawlinski — COMMENTED** [review]
Looks like it works well :+1: , but I found two errors: 

- when opening the story with icon component it appears (only in Storybook), but icons are rendering properly: 
Screenshot from 2022-03-11 12-16-09
- when I run unit tests this error appears:
Screenshot from 2022-03-11 11-06-57

**Comment by RafalDobrowolski** [comment]
> * when I run unit tests this error appears

Thank you and due to errors try to get latest version

**Review by justyna-13 — APPROVED** [review]

**Comment by RafalDobrowolski** [comment]
> > > * when I run unit tests this error appears
> > 
> > 
> > @AdamPawlinski thank you :) , and due to errors try to get the latest version
> 
> @RafalDobrowolski I tried, but with no result. Did you push any changes?

@AdamPawlinski today I pushed changes. But for me looks strange, because I don't have error related with storybook

**Review by AdamPawlinski — APPROVED** [review]
@RafalDobrowolski it looks like some bug on my side. Probably didn't upgrade latest changes. Now it works great :+1:

**Pull request merged**
