### PR TITLE
refactor: SfSeachbar replace input in searchbar & add SfIcon to SfInput

### LINKED ISSUE #882: [REFACTOR] SfSearchbar - replace <input> with SfInput
**Describe how this feature will help us improve**
Replace <input> with SFUI SfInput to keep the atomic approach.

Blocked by #849

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue
Closes #882

# Scope of work
Replace input with SfInput in SfSearchbar.
Blocked by #1238 because there are changes in adding icons api.

add SfIcon to SfInput: 
image

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed

### CODE REVIEW

**Comment by pspaczek** [comment]
@AdamPawlinski IMO we can back to this issues after #1128 and after that do something like that 
``` vue
<template>
  <SfInput
    class="sf-search-bar"
    :placeholder="placeholder"
    v-bind="$attrs"
    v-on="listeners"
    icon="search"
    icon-size="1.25rem"
    icon-color="secondary-variant"
   name="search"
  />
</template>
``` 
and of course others important thing for this issue

**Comment by AdamPawlinski** [comment]
I think this task is connected with two more: https://github.com/vuestorefront/storefront-ui/pull/1238

**Comment by justyna-13** [comment]
I think you're right. Both tasks you mentioned should be added to our new version and should be done before this one. We have a lot of components that use atoms or molecules with predefined props and if anyone would like to use it and change only one prop then has to write much more code instead of changing a value of an exact prop

**Comment by AdamPawlinski** [comment]
I put both types of icons (for password type and for other purposes) in input into one slot and left SfSearchbar with empty slot.

**Review by Baroshem — APPROVED** [review]
Looks good to me! Just rebase your branch and you can merge it :)

**Comment by Baroshem** [comment]
@AdamPawlinski 

I think you can rebase your branch and you should be ready to go!

**Review by aniamusial — APPROVED** [review]

**Comment by aniamusial** [comment]
@AdamPawlinski please resolve conflicts and update the changelog :)

**Review by justyna-13 — APPROVED** [review]

**Pull request merged**
