### PR TITLE
fix: updated form email input validation message

### LINKED ISSUE #2016: [BUG] Incorrect validation error message for email form input
**Describe the bug**
The email input for the Form story validation error message is a duplicate of the country input. It displays "Please choose your country".

**How to reproduce**
1. Go to https://docs.storefrontui.io/?path=/story/examples-form--form
2. Click in the Email input
3. Click out of the Email input
4. See incorrect validation error message

**Expected behavior**
This error message should notify the user to enter a valid email address

**Actual behavior**
The message is displaying a duplicate of the Country input validation error message.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by flyfishwv**
# Related issue
https://github.com/vuestorefront/storefront-ui/issues/2016
Closes #2016

# Scope of work
updated form email input validation message

# Screenshots of visual changes
Current Prod
image

Proposed fix
image

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
@flyfishwv Thanks for contributing. Could you please add changelog note? It's in stories -> releases  folder in 0.11.0, because it will be our next version. Just short info in 'chore' section about this change. Thanks.
Screenshot from 2021-09-27 14-18-02

**Comment by flyfishwv** [comment]
> @flyfishwv Thanks for contributing. Could you please add changelog note? It's in stories -> releases folder in 0.11.0, because it will be our next version. Just short info in 'chore' section about this change. Thanks.
> Screenshot from 2021-09-27 14-18-02

added and pushed

**Review by AdamPawlinski — APPROVED** [review]
Good work, thank you for your time :)

**Comment by flyfishwv** [comment]
@AdamPawlinski  do I merge the PR or do you all do that?

**Comment by AdamPawlinski** [comment]
I coudln't response immediately yesterday. But could you please do not merge by yourself. It is usually done by one of core team members and after two approvals. That's the information for the future :) Thanks for helping us. If you want to take another issue, please do not hesitate. I saw you noticed another bug. You probably could assign it by yourself.

**Pull request merged**
