### PR TITLE
chore: update core-js version

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue

Closes #

# Scope of work
Upgrade core-js version to latest stable, because mismatch between versions in projects could cause this error:
Screenshot from 2021-09-14 14-00-09

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by aniamusial — DISMISSED** [review]

**Comment by AdamPawlinski** [comment]
core-js updated to the latest version, but there is still bug when using nuxt module in a project, only when using exactly the same version of core-js in project it disappears  
Screenshot from 2021-11-17 13-50-42

**Comment by zloirock** [comment]
In most cases, such error means that you try to transpile `core-js` by itself and that causes circular dependencies.

**Comment by AdamPawlinski** [comment]
@zloirock  Thanks for the explanation. Can you suggest any solution for that?  :)

**Comment by zloirock** [comment]
Check your `babel` or `swc` config and ignore `core-js` folder in transpiling.

**Comment by AdamPawlinski** [comment]
@zloirock Thanks very much, I'll try that :)

**Pull request closed without merging**
