### PR TITLE
docs: fix contributing links

### PR DESCRIPTION
**Pull request by farukSRKNT**
# Related issue
Closes https://github.com/vuestorefront/storefront-ui/issues/2072

# Scope of work
redirect to correct URL 

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by aniamusial — DISMISSED** [review]

**Review by AdamPawlinski — DISMISSED** [review]

**Review by justyna-13 — DISMISSED** [review]

**Comment by aniamusial** [comment]
Hey @farukSRKNT any update on this? :)

**Comment by farukSRKNT** [comment]
Hi @aniamusial , sorry to keep you waiting. I had some issues with pre-commit hooks :) I had to use --no-verify flag. Please let me know if I broke the convention.

**Review by AdamPawlinski — APPROVED** [review]
Looks good, thank you :)

**Review by justyna-13 — APPROVED** [review]

**Comment by aniamusial** [comment]
thanks for your help @farukSRKNT :) feel free to take on any other task

**Comment by farukSRKNT** [comment]
You're welcome. I'll try to contribute more in the next days.

**Pull request merged**
