### PR TITLE
fix(sfGallery): Invalid prop: type check failed for prop "alt". Expec…

### PR DESCRIPTION
**Pull request by bartoszherba**
[Vue warn]: Invalid prop: type check failed for prop "alt". Expected String, got Undefined

# Related issue
-

# Scope of work
SfGallery molecule
- on the zoom out picture selected variable was cleared and the following error was thrown: "[Vue warn]: Invalid prop: type check failed for prop "alt". Expected String, got Undefined" as only the class of image component was toggled.

# Screenshots of visual changes
Screenshot 2022-02-01 at 09 35 27

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [x] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
@bartoszherba Hi, could you help me reproduce this error, because I tried it on commercetools integration and it works fine. Did you find it using 0.12.0 version of SFUI? 
gallery-zoom

**Comment by bartoszherba** [comment]
@AdamPawlinski 
Hey, we are using "@storefront-ui/vue": "^0.11.5"
The problem is because 
`removeZoom(index) {
      if (this.enableZoom) {
        this.pictureSelected = "";
        if (this.outsideZoom) return;
        this.$refs.sfGalleryBigImage[index].$el.children[0].style.transform =
            "scale(1)";
      }
    }`

pictureSelected is set to "" but in the same time SfImage is using it as and object with some data:
`<SfImage
              ref="imgZoom"
              class="sf-gallery__zoom"
              :src="pictureSelectedUrl"
              :width="imageWidth"
              :height="imageHeight"
              :lazy="false"
              :alt="pictureSelected.alt"
          />`

Therefore it breaks on zoom out.

**Comment by AdamPawlinski** [comment]
@bartoszherba Hi thanks for the explanation. I think this problem is already solved in 0.12.0 version, we added nuxt-img module implementation and changed zoom image behavior so it is always present (the `src` attribute is passed even when the image isn't used). Could you please test this bug with the new version? But there are a lot of other changes in this release and breaking changes too, so it needs some time to update it.

**Comment by AdamPawlinski** [comment]
I'm closing this task, @bartoszherba  please reopen it if this bug happens also on 0.12.0 version or higher.

**Pull request closed without merging**
