### PR TITLE
fix: sfCollectedProduct issue of input function in story and removed duplicate props

### LINKED ISSUE #2310: [BUG] SfCollectedProduct - error when changing the value in Storybook
**Describe the bug**
There is an error when trying to change the value in SfCollectedProduct on Storybook. 
Screenshot from 2022-03-08 09-20-09

**How to reproduce**

* go to SfCollectedProduct story on Storybook
* try to change product quantity 
* see the error 

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.

```
//Write code here
```

Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**

* Device: [e.g. iPhone6, Desktop]
* OS: [e.g. iOS8.1]
* Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-86) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by ymaheshwari1**
# Related issue

Closes #2310 

# Scope of work

- Removed this.input function
- Removed duplicate props

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by justyna-13 — COMMENTED** [review]
@ymaheshwari1 please add details about this change in our changelog :)

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 please add details about this change in our changelog :)

Sure

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 please add details about this change in our changelog :)

Done with adding the changes in the changelog

**Review by aniamusial — APPROVED** [review]

**Comment by aniamusial** [comment]
@ymaheshwari1 looking good, please resolve the conflicts :)

**Review by justyna-13 — APPROVED** [review]

**Pull request merged**
