### PR TITLE
fix: images are not shown on ssr

### LINKED ISSUE #1699: [BUG] images now are not shown on ssr
**Describe the bug**

All images now are not shown on ssr. Before refactor of SfImage there was noscript tag. 

**How to reproduce**
1. Go to demo page
2. Disable JS
3. See error

**Expected behavior**
Images are shown on ssr

**Actual behavior**
No images on ssr

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue

Closes #1699 

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by Baroshem — DISMISSED** [review]
Checked it on nuxt branch. Works great! The only thing left is to adjust your branch to develop branch :)

**Comment by Baroshem** [comment]
@AdamPawlinski  @justyna-13 

Adam, please check this pull request. If it's ok, I think we are ready to merge it :)

**Review by Baroshem — APPROVED** [review]
Looks good!

**Comment by justyna-13** [comment]
changed branch for hotfix.0.10.5

**Pull request closed without merging**
