### PR TITLE
fix: add missing glob dependency

### PR DESCRIPTION
**Pull request by samriley**
# Scope of work
Added a missing dependency causing ```Error: @storefront-ui/vue tried to access glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.``` when using yarn2

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by Baroshem** [comment]
Let's discuss addition of this library for the next version of SFUI

**Comment by Baroshem** [comment]
Hi @samriley 

I added this issue to 0.10.9 roadmap. Could you please change the base branch from develop to 0.10.9?

**Comment by samriley** [comment]
just fixing up the pr - will have it updated shortly

**Comment by Baroshem** [comment]
@samriley 
On a second thought, projects that were reporting this issue needed different version of yarn to correctly working. What is your case when you discovered this issue? The easiest workaraound is to change the version of yarn.

**Comment by samriley** [comment]
the issue is that yarn2 (berry) refuses to execute dependencies that aren't specified in the package.json. This is an issue since the postinstall script executes `create-index-files.js` which includes the reference to `glob`.
```Error: @storefront-ui/vue tried to access glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.```

Though this is an interesting question - should it be executing that postinstall? it looks like its also executed prepublish? leaving it at prepublish only would allow it to be specified as a dev dependency.

Steps to reproduce, install yarn globally, create a new repo, yarn init and update yarn to berry (`yarn set version berry`), finally try to install `@storefront-ui/vue`.

**Comment by AdamPawlinski** [comment]
@samriley Could you please move this dependency to devDependency and add changelog note, because we want to release new version next week? Thank you for helping me solve this.

**Comment by merceyz** [comment]
Moving it to `devDependencies` defeats the whole purpose of adding it, `glob` is used by the `postinstall` script here
https://github.com/vuestorefront/storefront-ui/blob/704fc996eaa80acfd0511541586b067b24a895b3/packages/vue/scripts/create-index-files.js#L4 and is therefor a runtime dependency and needs to be declared in `dependencies`

**Comment by AdamPawlinski** [comment]
Ok, you are right. Let's leave it like this and I add changelog as we want to prepare 0.10.9 release.

**Pull request merged**
