### PR TITLE
Vue3 upgrade draft Atoms #966

### PR DESCRIPTION
**Pull request by abskj**
# Related issue

https://github.com/vuestorefront/storefront-ui/issues/966
Makes progress on #966

# Scope of work (not in order of commits)
 - updated vue to vue 3
 - added vue/compat and set up vue migration build
 - updated main.js/similiar files to work with vue 3
 - updated unit testing dependencies to work with vue 3
 -  set all atom components to run in vue
 - refactored atom components to work with vue 3 mode of compatibility build
 - refactored the unit tests if they were throwing error
 - validated manually the atom components
 - ensured success of unit tests
 
# Issues at this point in this scope(atoms)
- SfBullets gives a runtime error. 
- attributes binding may be repeated for some components not using inheritAttrs: false (https://v3.vuejs.org/guide/migration/v-bind.html#_3-x-syntax)
- Something else not detected by vue compatibility build

# What next
- extend the same approach to molecules and organisms
- update e2e dependencies if required and make it work
- Ensure storybook works
- Create package "next" analogous to "nuxt"
- Release?

# So
Maintainers and contributers, please review the changes. This is a draft build and hence it fails at project level in many tests. Hence it had to skip multiple things in checklists. Please provide feedback on any aspects you think can be improved.
Your feedback will help with proceeding with this change on other components.

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Comment by Baroshem** [comment]
Hi @undercoverGod 

Thank you very much for this PR. This looks really promising! I will take a look at it in the upcoming days and I will also invite other core team members to take a look at that as this feature is crucial for us.

**Comment by undercoverGod** [comment]
@Baroshem  In that case we can duplicate and rename `vue` folder and save this preliminary change to next branch that will then have redundant package `next` which is just copy of `vue`. So that in future changes can be better compared and at the same time not need structural change before approval.

**Comment by AdamPawlinski** [comment]
@undercoverGod  Hi, could you please let me know if you can run Storybook with refactored components? I upgraded Storybook to the version which supports Vue3, but it still doesn't work. Did you manage to that?

**Comment by undercoverGod** [comment]
@AdamPawlinski  No I could not. As storybook is new to me I did not try further. I will see if I can get it running now.

**Comment by undercoverGod** [comment]
Hi I created new project in the structure that was discussed. Using vite in this project and have moved the atoms to there, storybook and unit test is running though will be needing lot of fixes but I believe this might be good place to start doing changes incrementally. Please let me know your thoughts.
https://github.com/undercoverGod/storefront-ui/tree/next

**Comment by wxs77577** [comment]
How can I help?

**Pull request closed without merging**
